trigger:
- none
pool:
  vmImage: ubuntu-latest

variables:
- group: Variable Group

stages:
  - stage: Build
    jobs:
      - job: 'b1'
        steps:
        - script: echo Hello, world! DevOps _ Repo main branch
          displayName: 'Run a one-line script'

  - stage: Test
    jobs:
      - job: 'ppb1'
        steps:
        - script: echo Hello, world! 
          displayName: 'Run a one-line script'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(System.DefaultWorkingDirectory)'
            ArtifactName: 'Build Artifact'
            publishLocation: 'container'
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              
              echo 'Hello world. $(Build.Repository.ID)'

        # - task: PublishBuildArtifacts@1
        #   inputs:
        #     PathtoPublish: 'target'
        #     ArtifactName: 'Build Artifact'
        #     publishLocation: 'container'

  - stage: Deploy
    jobs:
      - job: 'p1'
        steps:
            - script: echo Hello, world!
            - task: ServiceNow-DevOps-Server-Change-Acceleration@1
              inputs:
                  connectedServiceName: 'empmanuutah-Manohar_Project-ServiceNow DevOps Service Connection'
                  changeRequestDetails: |
                    {
                      "setCloseCode": false,
                      "autoCloseChange": true,
                      "attributes": {
                        "category": "DevOps",
                        "priority": "2",
                        "comments": "This is a sample pipeline script to be added in change step",
                        "work_notes": "Update this to work_notes"
                      }
                    }
