# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Action with Env

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
env:
  SNOW_URL: ${{ secrets.SNOW_URL }}
  SNOW_TOKEN: ${{ secrets.SNOW_TOKEN }}
  SNOW_TOOLID: ${{ secrets.SNOW_TOOLID }}
  CI_PIPELINE_ID: ${{ env.GITHUB_RUN_ID }}
  CI_API_V4_URL: ${{ env.GITHUB_SERVER_URL }}
  CI_JOB_ID: ${{ env.GITHUB_RUN_ID }}
  CI_PROJECT_TITLE: ${{ env.GITHUB_RUN_ID }}
  CI_JOB_NAME: ${{ env.GITHUB_REPOSITORY}+'/'+ env.GITHUB_WORKFLOW }}
  CI_PROJECT_PATH: ${{ env.GITHUB_JOB }}
  CI_REPOSITORY_NAME: ${{ env.CI_REPOSITORY_NAME }}
  CI_RUN_ATTEMPT: ${{ env.GITHUB_RUN_ATTEMPT }}
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with: 
        arguments: build

  
  ServiceNowDevOpsChange:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: mdavireddy/sndevops:2.0.0

    steps:
    - name : create change
      run: | 
        sndevopscli create change -p "{\"changeStepDetails\":{\"timeout\":3600,\"interval\":100},\"autoCloseChange\":true,\"attributes\":{\"short_description\":\"G Venkata Automated Software Deployment\",\"description\":\"Automated Software Deployment.\",\"assignment_group\":\"a715cd759f2002002920bde8132e7018\",\"implementation_plan\":\"Software update is tested and results can be found in Test Summaries Tab.\",\"backout_plan\":\"When software fails in production, the previous software release will be re-deployed.\",\"test_plan\":\"Testing if the software was successfully deployed or not\"}}"
 
  ServiceNowUpdateDevOpsChange:
    runs-on: ubuntu-latest
    needs: ServiceNowDevOpsChange
    container:
      image: mdavireddy/sndevops:2.0.0

    steps:
    - name : update change
      run: |
        sndevopscli get change #If we are placing get change cli command in the same job where we are creating change then no need to mention the changeDetails.
        sndevopscli update change -p "{\"short_description\":\"Updated Automated Software Deployment\",\"description\":\"Automated Software Deployment.\",\"assignment_group\":\"a715cd759f2002002920bde8132e7018\",\"implementation_plan\":\"Software update is tested and results can be found in Test Summaries Tab.\",\"backout_plan\":\"When software fails in production, the previous software release will be re-deployed.\",\"test_plan\":\"Testing if the software was successfully deployed or not\"}"
         
        

       
