name: Action with Env

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
env:
  SNOW_URL: ${{ secrets.SNOW_URL }}
  SNOW_TOKEN: ${{ secrets.SNOW_TOKEN }}
  SNOW_TOOLID: ${{ secrets.SNOW_TOOLID }}
  CI_PIPELINE_ID: ${{ github.run_id }}
  CI_API_V4_URL: ${{ github.server_url }}
  CI_JOB_ID: ${{ github.run_id }}
  CI_PROJECT_PATH: ${{ github.job }}
  CI_REPOSITORY_NAME: ${{ github.repository }}
  CI_RUN_ATTEMPT: ${{ github.run_attempt }}
  CI_PROJECT_TITLE: ${{ github.repository }}/${{github.workflow}}
  CI_COMMIT_BRANCH: ${{ github.ref_name }}
  CI_WORKFLOW_NAME: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        run: |
          echo 'hello '

  ServiceNowDevOpsSecurityScan:
     runs-on: ubuntu-latest
     needs: build
     container:
       image: mdavireddy/sndevops:2.0.0
     env:
       CI_JOB_NAME: "ServiceNowDevOpsSecurityScan"

     steps:
       - name: security scan
         run: |
           sndevopscli create securityScan -p "{\"scanner\": \"Veracode\", \"applicationName\": \"\", \"buildVersion\": \"\", \"securityToolId\": \"\"}"
  
